# This is an example mods.toml file. It contains the data relating to the loading mods.
modLoader="javafml" #mandatory
license="ARR"

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[6,)" #mandatory

# A URL to refer people to when problems occur with this mod
issueTrackerURL=""

[[mods]] #mandatory
modId="taczmagazines" #mandatory
version="0.0.7" #mandatory
displayName="TaCZ: Magazines" #mandatory
updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/taczmagazines"
logoFile=""
credits=""
authors="Raiiiden"
description='''Magazine system for TaCZ'''

[[dependencies.taczmagazines]]
modId="forge"
mandatory=true
versionRange="[6,)"
ordering="NONE"
side="BOTH"

[[dependencies.taczmagazines]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"
